# Generated by Django 5.1.15 on 2026-09-28 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('target_role', models.CharField(blank=True, default='Full Stack Developer', max_length=150)),
                ('college', models.CharField(blank=True, default='', max_length=255)),
                ('degree', models.CharField(blank=True, default='', max_length=150)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('work_mode_preference', models.CharField(choices=[('REMOTE', 'Remote Only'), ('HYBRID', 'Hybrid'), ('ONSITE', 'On-site'), ('FLEXIBLE', 'Flexible / Any')], default='FLEXIBLE', max_length=20)),
                ('expected_salary', models.CharField(blank=True, default='', max_length=100)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
