# Generated by Django 5.1.15 on 2026-09-28 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('job_url', models.URLField(blank=True, default='')),
                ('location', models.CharField(default='Remote / Flexible', max_length=150)),
                ('employment_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract / Project')], default='INTERNSHIP', max_length=20)),
                ('experience_level', models.CharField(blank=True, default='Fresher / 0-1 Years', max_length=100)),
                ('education_requirement', models.CharField(blank=True, default='', max_length=255)),
                ('salary_range', models.CharField(blank=True, default='', max_length=100)),
                ('raw_description', models.TextField(help_text='Full original job description text')),
                ('parsed_requirements', models.JSONField(blank=True, default=dict, help_text='Structured requirements: responsibilities, requirements, preferred criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=True, help_text='True if mandatory/critical, False if nice-to-have')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_demands', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'ordering': ['-is_critical', 'skill__name'],
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
