# Generated by Django 5.1.15 on 2026-09-28 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(default='Full Stack Python Developer', max_length=150)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Roadmap',
                'verbose_name_plural': 'Learning Roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical (Must-Have for Role)'), ('IMPORTANT', 'Important (Competitive Advantage)'), ('OPTIONAL', 'Optional (Nice-to-Have)')], default='CRITICAL', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('estimated_hours', models.FloatField(default=6.0)),
                ('practice_task', models.TextField(help_text='Hands-on mini-project or coding task to solidify concept')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.learningroadmap')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_tasks', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Learning Task',
                'verbose_name_plural': 'Learning Tasks',
                'ordering': ['week_number', 'priority'],
            },
        ),
    ]
