# Generated by Django 5.1.15 on 2026-09-28 12:54

import apps.resumes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.resumes.models.resume_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=False)),
                ('match_score', models.FloatField(default=0.0, help_text='InternTrack Resume Match Score (0-100)')),
                ('score_breakdown', models.JSONField(default=dict, help_text='Component breakdown: skills, projects, keywords, education, experience')),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted structured sections: contact, education, skills, projects, experience, certifications')),
                ('improvement_suggestions', models.JSONField(default=list, help_text='Actionable suggestions to improve resume impact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('context', models.CharField(blank=True, default='', max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='resumes.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_instances', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Resume Skill',
                'verbose_name_plural': 'Resume Skills',
                'ordering': ['-frequency'],
                'unique_together': {('resume', 'skill')},
            },
        ),
    ]
