# Generated by Django 5.1.15 on 2026-09-28 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('LANGUAGES', 'Programming Languages'), ('FRAMEWORKS', 'Web & App Frameworks'), ('DATABASES', 'Databases & Storage'), ('DEVOPS', 'DevOps & Infrastructure'), ('CLOUD', 'Cloud Platforms'), ('FUNDAMENTALS', 'CS Fundamentals & Architecture'), ('TESTING', 'Testing & QA'), ('TOOLS', 'Developer Tools & VCS'), ('SOFT_SKILLS', 'Soft Skills & Leadership')], default='LANGUAGES', max_length=30)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names, acronyms, or syntax')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('BEGINNER', 'Beginner (Academic / Learning)'), ('INTERMEDIATE', 'Intermediate (Built Projects)'), ('ADVANCED', 'Advanced (Production Experience)'), ('EXPERT', 'Expert (Mastery / Architecture)')], default='INTERMEDIATE', max_length=20)),
                ('years_of_experience', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'ordering': ['skill__name'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
