from django.urls import path
from .views import (
    LandingPageView,
    LoginPageView,
    RegisterPageView,
    DashboardView,
    ProfileView,
    ResumesView,
    ResumeAnalyzeView,
    JobsView,
    JobAddView,
    JobDetailPageView,
    ApplicationsView,
    ApplicationDetailView,
    SkillsView,
    SkillGapView,
    AnalyticsView,
    InterviewsView,
    LearningView,
    NotificationsView,
    SettingsView,
    ReportsView
)

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing'),
    path('login/', LoginPageView.as_view(), name='login-page'),
    path('register/', RegisterPageView.as_view(), name='register-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard-page'),
    path('profile/', ProfileView.as_view(), name='profile-page'),
    path('resumes/', ResumesView.as_view(), name='resumes-page'),
    path('resume/analyze/', ResumeAnalyzeView.as_view(), name='resume-analyze-page'),
    path('jobs/', JobsView.as_view(), name='jobs-page'),
    path('jobs/add/', JobAddView.as_view(), name='job-add-page'),
    path('jobs/<uuid:pk>/', JobDetailPageView.as_view(), name='job-detail-page'),
    path('applications/', ApplicationsView.as_view(), name='applications-page'),
    path('applications/<uuid:pk>/', ApplicationDetailView.as_view(), name='application-detail-page'),
    path('skills/', SkillsView.as_view(), name='skills-page'),
    path('skill-gap/', SkillGapView.as_view(), name='skill-gap-page'),
    path('analytics/', AnalyticsView.as_view(), name='analytics-page'),
    path('interviews/', InterviewsView.as_view(), name='interviews-page'),
    path('learning/', LearningView.as_view(), name='learning-page'),
    path('notifications/', NotificationsView.as_view(), name='notifications-page'),
    path('settings/', SettingsView.as_view(), name='settings-page'),
    path('reports/', ReportsView.as_view(), name='reports-page'),
]
