# Generated by Django 5.1.15 on 2026-09-28 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, help_text='e.g. Python, Django, SQL, REST API, Git, Docker', max_length=50)),
                ('question_type', models.CharField(choices=[('TECHNICAL', 'Technical Concepts'), ('CODING', 'Coding & DSA'), ('HR', 'HR & Behavioral (STAR)'), ('SQL', 'SQL Queries & Optimization'), ('PROJECT', 'Project & Architecture Deep Dive')], default='TECHNICAL', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('question_text', models.TextField()),
                ('model_answer', models.TextField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('HR', 'HR / Recruiter Screening'), ('TECHNICAL', 'Technical Round 1'), ('CODING', 'Live Coding / DSA'), ('MANAGERIAL', 'Managerial / Team Fit'), ('FINAL', 'Final Round / Leadership')], default='TECHNICAL', max_length=20)),
                ('interview_type', models.CharField(choices=[('VIDEO', 'Video Call (Google Meet, Zoom, Teams)'), ('PHONE', 'Phone Call'), ('ONSITE', 'On-site / In-person'), ('ASYNC', 'Recorded / Automated (HireVue, etc.)')], default='VIDEO', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('questions_asked', models.TextField(blank=True, default='', help_text='Questions asked during the actual interview')),
                ('feedback', models.TextField(blank=True, default='', help_text='Interviewer feedback or self-reflection notes')),
                ('result', models.CharField(choices=[('SCHEDULED', 'Upcoming / Scheduled'), ('COMPLETED', 'Completed / Awaiting Feedback'), ('PASSED', 'Passed (Advancing)'), ('FAILED', 'Did Not Pass'), ('CANCELLED', 'Cancelled / Rescheduled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.TextField()),
                ('score', models.FloatField(default=0.0, help_text='Score 0-100')),
                ('feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='interviews.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Attempt',
                'verbose_name_plural': 'Interview Attempts',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
