# Generated by Django 5.1.15 on 2026-09-28 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INTERVIEW_REMINDER', 'Interview Reminder'), ('APPLICATION_DEADLINE', 'Application Deadline'), ('FOLLOW_UP_DUE', 'Follow-up Due'), ('SKILL_GAP_ALERT', 'Skill Gap Alert'), ('PROFILE_INCOMPLETE', 'Profile Incomplete'), ('APPLICATION_UPDATE', 'Application Update'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
